.PHONY: clean All

All:
	@echo "----------Building project:[ breakout - Debug ]----------"
	@cd "breakout" && "$(MAKE)" -f  "breakout.mk" && "$(MAKE)" -f  "breakout.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ breakout - Debug ]----------"
	@cd "breakout" && "$(MAKE)" -f  "breakout.mk" clean
