.PHONY: clean All

All:
	@echo "----------Building project:[ flip_flop_irq - Debug ]----------"
	@cd "flip_flop_irq" && "$(MAKE)" -f  "flip_flop_irq.mk" && "$(MAKE)" -f  "flip_flop_irq.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ flip_flop_irq - Debug ]----------"
	@cd "flip_flop_irq" && "$(MAKE)" -f  "flip_flop_irq.mk" clean
