.PHONY: clean All

All:
	@echo "----------Building project:[ graphic_display - Debug ]----------"
	@cd "graphic_display\graphic_display" && "$(MAKE)" -f  "graphic_display.mk" && "$(MAKE)" -f  "graphic_display.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ graphic_display - Debug ]----------"
	@cd "graphic_display\graphic_display" && "$(MAKE)" -f  "graphic_display.mk" clean
