.PHONY: clean All

All:
	@echo "----------Building project:[ FlipFlopIrq - Debug ]----------"
	@cd "FlipFlopIrq" && "$(MAKE)" -f  "FlipFlopIrq.mk" && "$(MAKE)" -f  "FlipFlopIrq.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ FlipFlopIrq - Debug ]----------"
	@cd "FlipFlopIrq" && "$(MAKE)" -f  "FlipFlopIrq.mk" clean
