.PHONY: clean All

All:
	@echo "----------Building project:[ 4-1 - Debug ]----------"
	@cd "4-1" && "$(MAKE)" -f  "4-1.mk" && "$(MAKE)" -f  "4-1.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ 4-1 - Debug ]----------"
	@cd "4-1" && "$(MAKE)" -f  "4-1.mk" clean
